export const OFFLINE_DOWNLOAD_CANCELLED_CODE = 'offline_download_cancelled';
export const OFFLINE_RASTER_DOWNLOAD_CANCELLED_CODE = 'OFFLINE_RASTER_DOWNLOAD_CANCELLED';
export const OFFLINE_EMPTY_TILE_DATA_URL =
  'data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=';
